FROM node:12.16.2-alpine3.9 as build
WORKDIR /app
ADD public ./public
COPY package.json ./
RUN yarn
COPY .env.local ./
ADD src ./src
RUN yarn run build

FROM nginx:1.18.0-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]